version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telegram-bot-base"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pydelgwo9fde"
s3_prefix = "telegram-bot-base"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
