name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: yarn install
      - run: yarn build
      - name: Build using SAM
        run: sam build
        env:
          SAM_CLI_TELEMETRY: 0
      - name: Deploy
        run: sam deploy --parameter-overrides ParameterKey=TelegramBotToken,ParameterValue=${{ secrets.TELEGRAM_BOT_TOKEN }}
